# RudiCrates v0.9.4 Config
# 
# The opening of crates is disabled by default, set the crates you want to use
# in the 'crates:' section first.
#
# 
#                                [Example]
# crates:
#   gold:                          - The crate-name (used for ingame commands)
#     displayname: '&6Gold-Crate'  - The crate-displayname der Crate (shown in the crate-menu)
#     material: 'GOLD_BLOCK'       - The material of the crate-item in the crate menu
#     slot: 15                     - The slot of the crate-item
#
#     key:                         - Section for not-virtual keys
#       material:                  - Material of the key
#       name:                      - Name of the key
#       enchant:                   - Visual enchantment (true/false)
#       lore:                      - Lore of the key
#
# Liste für Materialien [1.16.5] -> https://helpch.at/docs/1.16.5/org/bukkit/Material.html


# When 'usemysql' is false, the crates (keys) will be saved in .yml files.
# Die table and the database will be created if they not exist.
usemysql: false

mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'name'
  password: 'password'
  database: 'rudicrates'
  
# A message will be sent to all players, when an item gets pulled with this chance or less.
broadcast: 5.0
# for limited items
broadcastlimited: 5.0
# # A firework will be spawned above the player, when an item gets pulled with this chance or less.
firework: 10.0

# Removes limited items automaticly from the crate, when the limitation is reached.
removelimiteditems: false

# Inventory name of the crate-menü
inventorytitle: 'Crate Opening ⚄'

# Inventory rows (1-6)
inventoryrows: 5

# Puts a red glass pane into the crate-menu to close it
usecloseinventory: false
closeinventoryslot: 45
  
# Will be displayed while a crate is beeing opened
windisplayitem: 'HOPPER'
windisplayname: '§c↓ §6Your win §c↓'
windisplayitemenchant: true

# Empty slots in the crate-menu will be filled by with this item
usefillitem: true
fillitem:
  material: 'GRAY_STAINED_GLASS_PANE'
  name: ''
  enchanted: false
  durability: 0 # <- For 1.8.8 + 1.12.2
  
# The highest amount of keys that can be given with /key
max_key_amount: 100
  
# Crate settings
# The wins of the crates will be saved in .yml files with the name of the crate.
# Wins can be added ingame. More information with the command '/rc help'.
# (The win chances do not have to add up to 100)
#
# Restart the plugin after you added the crates. RudiCrates will create the .yml files for the crates.
# When you added items to your crates (ingame with /addtocrate), set 'enabled' to true.

crates:
  
  wood:
    displayname: '&eWood Crate'
    material: 'LOG'
    slot: 11
    key:
      material: 'TRIPWIRE_HOOK'
      name: '&eWood-Crate Key'
      enchant: false
      lore:
        - '§6Opens a wood crate'

  iron:
    displayname: '&f&lIron Crate'
    material: 'IRON_BLOCK'
    slot: 14
    key:
      material: 'TRIPWIRE_HOOK'
      name: '&f&lIron-Crate Key'
      enchant: true
      lore:
        - '&6Opens an iron crate'
        - '§c- Example Test'

  diamond:
    displayname: '&b&oDiamond Crate'
    material: 'DIAMOND_BLOCK'
    slot: 17
    key:
      material: 'DIAMOND'
      name: '&bDiamond Key'
      enchant: true
      lore:
        - ' '
        - '&dOpens a diamond crate'
        - '&aYou can change or remove this text'
        - '&cin the config.'

# Enables / Disables the opening of crates
# useful to avoid errors while adding items etc.
# (can also be changed ingame via /rc toggle) *currently disabled
enabled: false