# RudiCrates v0.9.5 Config
# 
# The opening of crates is disabled by default, set the crates you want to use
# in the 'crates:' section first.
#
# When using color codes, write text within apostrophes. ( e.g. menu_title: '&cCrate Opening' ) 
#
#                                [Example]
# crates:
#   gold:                          - The crate-name (used for in-game commands)
#     displayname: '&6Gold-Crate'  - The crate-displayname der Crate (shown in the crate-menu)
#     material: 'GOLD_BLOCK'       - The material of the crate-item in the crate menu
#     slot: 15                     - The slot of the crate-item
#
#     key:                         - Section for non-virtual keys
#       material: 'TRIPWIRE_HOOK'  - Material of the key
#       name: '&6Gold-Crate Key'   - Name of the key
#       enchant: true              - Visual enchantment (true/false)
#       lore:                      - Lore of the key
#         - '&3you can open a'
#         - '&6Gold-Crate with this key' 
#
# List of Materials [1.16.5] -> https://helpch.at/docs/1.16.5/org/bukkit/Material.html
#
#
# When 'usemysql' is false, the crates (keys) will be saved in .yml files.
# MySQL table and database will be created if they not exist.
usemysql: false
mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'name'
  password: 'password'
  database: 'rudicrates'
  
pull_events:
  # The message (crates.self/other.broadcast) will be sent to all online players, when an item gets pulled with this chance or less.
  broadcast: 5.0
  # Broadcast for limited items (crates.self/other.limited) will be sent to all online players.
  limited: 5.0
  # A firework will be spawned above the player who opened the crate, when an item gets pulled with this chance or less.
  firework: 10.0

inventories:
  menu_title: '<#value#>'
  menu_rows: 3 # (1-6)

# For 1.8.8 users: \u2684 is a die, \u2193 is an arrow facing down

items:
  # Puts a red glass pane into the crate-menu to close it
  use_close: true
  close_slot: 27
  close:
    name: '&cClose menu'
    material: '<#value#>'
    enchant: false
    durability: 14
  
  # Empty slots in the crate-menu will be filled with this item
  use_fill: true
  fill:
    name: ' '
    material: '<#value#>'
    enchant: false
    durability: 15
  
  # Item on the 5. slot, displayed while opening a crate
  display: 
    name: '<#value#>'
    material: 'HOPPER'
    enchant: true

available_crate_blocks:
  - 'CHEST'
  - 'ENDER_CHEST'
  - 'BLACK_SHULKER_BOX'

# Removes limited items automatically from the crate, when the limitation is reached.
remove_limited_items: false

# Files of crates wich are not in use (not listed under 'crates.') will be deleted.
delete_unused_crate_files: false

# Enables / Disables item-keys
use_item_keys: true

# The highest amount of keys that can be given with /key
max_key_amount: 100

# The highest amount of items that can be put in a crate. (values above 1000 are not recommended)
max_items_per_crate: 250

# Crate settings
# The wins of the crates will be saved in .yml files with the name of the crate.
# Wins can be added in-game. More information with the command '/rc help'.
# (The win chances do not have to add up to 100)
#
# Restart the plugin after you added the crates, RudiCrates will create the .yml files for them.
# When you added items to your crates (/addtocrate), set 'enabled' to true or use '/rc toggle'.

crates:
  
  wood:
    displayname: '&eWood Crate'
    material: '<#value#>'
    slot: 11
    key:
      material: 'TRIPWIRE_HOOK'
      name: '&eWood-Crate Key'
      enchant: false
      lore:
        - '&6Opens a wood crate'

  iron:
    displayname: '&f&lIron Crate'
    material: 'IRON_BLOCK'
    slot: 13
    key:
      material: 'TRIPWIRE_HOOK'
      name: '&f&lIron-Crate Key'
      enchant: true
      lore:
        - '&6Opens an iron crate'
        - '&c- Example Text'

  diamond:
    displayname: '&b&oDiamond Crate'
    material: 'DIAMOND_BLOCK'
    slot: 15
    key:
      material: 'DIAMOND'
      name: '&bDiamond Key'
      enchant: true
      lore:
        - ' '
        - '&dOpens a diamond crate'
        - '&aYou can change or remove this text'
        - '&cin the config.'

# Enables / Disables the opening of crates
# useful to avoid errors while adding items etc.
# (can also be changed in-game via /rc toggle)
enabled: false