name: RudiCrates
version: '${project.version}'
main: de.laparudi.rudicrates.RudiCrates
api-version: 1.13
author: LapaRudi
description: RudiCrates Crate-Opening
softdepend:
  - PlugMan

commands:
  rudicrates:
    description: Help and reload command
    aliases: [rc, rcrates]
  getcrateblock:
    description: Give you a crate opening block
  key:
    description: Add or remove crates from players
    aliases: [cratekey, keys]
  addtocrate:
    description: Add the item in your hand to a crate
    aliases: addcrateitem
  removefromcrate:
    description: Remove an item from a crate
    aliases: removecrateitem
  editchance:
    description: Change the win chance of an item
    aliases: setchance
  bindcommand:
    description: Add a command to a crate-item that will be executed when the item gets pulled
    aliases: addcommand
  setvirtual:
    description: Set a crate-item virtual
    aliases: virtual
  setlimited:
    description: Limit a crate-item to a specific amount
    aliases: limited

permissions: 
  rudicrates.*:
    description: Access to all RudiCrates features
  rudicrates.reload:
    description: Access to /rudicrates reload
  rudicrates.toggle:
    description: Access to /rudicrates toggle
  rudicrates.getcrateblock:
    description: Access to /getcrateblock
  rudicrates.key:
    description: Access to /key
  rudicrates.addtocrate:
    description: Access to /addtocrate
  rudicrates.removefromcrate:
    description: Access to /removefromcrate
  rudicrates.editchance:
    description: Access to /editchance
  rudicrates.bindcommand:
    description: Access to /bindcommand
  rudicrates.setvirtual:
    description: Access to /setvirtual
  rudicrates.setlimited:
    description: Access to /setlimited